map/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.map, name='map'),
 ]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('map/', include('map.urls')),
    path('sightings/', include('sightings.urls')),
    path('admin/', admin.site.urls),

 ]

sightings/urls.py
from django.urls import path, re_path
from . import views


app_name = 'sightings'

urlpatterns = [
        path('', views.list_of_squirrels, name='list_of_squirrels'),
        path('add/', views.create_squirrel, name='create_squirrel'),
        path('stats/', views.stats, name='stats'),
        re_path('^(?P<Unique_Squirrel_ID>.*)/$', views.update, name='update')
]

map/models.py
from django.db import models

# Create your models here.

sightings/models.py
from django.db import models

class Squirrel(models.Model):
    Latitude = models.FloatField( )

    Longitude = models.FloatField( )

    Unique_Squirrel_ID = models.CharField(
        max_length=100,
        unique=True,
    )

    Shift = models.CharField(
        max_length=100,
    )

    Date = models.DateField(
        max_length=100,
        blank=True,
    )

    Age = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )

    Primary_Fur_Color = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )

    Location = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )

    Specific_Location = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )       

    Running = models.BooleanField(blank=True)     

    Chasing = models.BooleanField(blank=True)  
    
    Climbing = models.BooleanField(blank=True)  

    Eating = models.BooleanField(blank=True)

    Foraging = models.BooleanField(blank=True)

    Other_Activitites = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )

    Kuks = models.BooleanField(blank=True)

    Quaas = models.BooleanField(blank=True)

    Moans = models.BooleanField(blank=True)

    Tail_flags = models.BooleanField(blank=True)

    Tail_twitches = models.BooleanField(blank=True)

    Approaches = models.BooleanField(blank=True)

    Indifferent = models.BooleanField(blank=True)

    Runs_from = models.BooleanField(blank=True)
    
    def __str__(self):
        return self.Unique_Squirrel_ID

sightings/forms.py
from django.forms import ModelForm
from .models import Squirrel

class SquirrelForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = '__all__'


class UpdatingForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = [
            'Latitude',
            'Longitude',
            'Unique_Squirrel_ID',
            'Shift',
            'Date',
            'Age',
        ]

map/views.py
from django.shortcuts import render
from sightings.models import Squirrel

def map(request):
    
    squirrels = Squirrel.objects.all()[:100]

    context = { 'squirrels' : squirrels }

    return render(request,'map/map.html',context)

sightings/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from .models import Squirrel
from .forms import SquirrelForm, UpdatingForm
from django.http import HttpResponse

from django.db.models import Avg, Max, Min, Count



def list_of_squirrels(request):
    squirrels = Squirrel.objects.all()
    context = {
            'squirrels': squirrels,
    }

    return render(request, 'sightings/list.html', context)

def update(request, Unique_Squirrel_ID):
    squirrel = get_object_or_404(Squirrel, Unique_Squirrel_ID=Unique_Squirrel_ID)
    if request.method == 'POST':
        form = UpdatingForm(request.POST, instance=squirrel)
        if form.is_valid():
            form.save()
            return redirect(f'/sightings/')
    else:
        form = UpdatingForm(instance=squirrel)
    
    context ={
        'form':form,
        'sqid':Unique_Squirrel_ID,
    }

    return render(request, 'sightings/update.html', context)


def create_squirrel(request):
    if request.method == "POST":
        form = SquirrelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/sightings/")
    else:
        form = SquirrelForm()
    context = {
            'form':form,
    }
    return render(request, 'sightings/add.html', context)

def stats(request):
    squirrels = Squirrel.objects.all()
    a = len(squirrels)
    b = squirrels.aggregate(avg_latitude=Avg('Latitude'))
    c = squirrels.aggregate(avg_longitude=Avg('Longitude'))
    d = list(squirrels.values_list('Shift').annotate(Count('Shift')))
    e = list(squirrels.values_list('Age').annotate(Count('Age')))
    f = list(squirrels.values_list('Primary_Fur_Color').annotate(Count('Primary_Fur_Color')))

    context = {
        "a": a,
        "b": b,
        "c": c,
        "d": d,
        "e": e,
        "f": f,
    }

    return render(request, 'sightings/stats.html',context)

map/templates/map/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for sighting in squirrels  %}
          var point_lat_lon = [{{ sighting.Longitude }}, {{ sighting.Latitude }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

sightings/templates/sightings/add.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

sightings/templates/sightings/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>sightings</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/4.0.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-default ">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/sightings">Squirrel Tracker</a></div>
        <ul class="nav navbar-nav ">
          <li>
            <a href="/map">Map</a></li>
          <li>
            <a href="/sightings/add">Add A New Sighting</a></li>
          <li>
            <a href="/sightings/stats">Statistics</a></li>
	</ul>
      </div>
    </nav>
    <table class="table table-bordered table-responsive table-striped table-hover">
      <caption>Unique Sightings of Squirrel {{ID}}</caption>
      <thead class="thead-dark">
        <tr>
          <th>Unique Squirrel ID</th>
	  <th>{{squirrel.Unique_Squirrel_ID }}</th>
	</tr>
      </thead>
      <tbody>
	<tr>
          <td>Longitude</td>
	  <td>{{squirrel.Longitude}}</td>
	</tr>
        <tr>
          <td>Shift</td>
          <td>{{squirrel.Shift}}</td>
        </tr>
        <tr>
          <td>Date</td>
          <td>{{squirrel.Date}}</td>
        </tr>
        <tr>
          <td>Age</td>
          <td>{{squirrel.Age}}</td>
        </tr>
        <tr>
          <td>Primary Fur Color</td>
          <td>{{squirrel.Primary_Fur_Color}}</td>
        </tr>
        <tr>
          <td>Location</td>
          <td>{{squirrel.Location}}</td>
        </tr>
        <tr>
          <td>Specific Location</td>
          <td>{{squirrel.Specific_Location}}</td>
        </tr>
        <tr>
          <td>Running</td>
          <td>{{squirrel.Running}}</td>
        </tr>
        <tr>
          <td>Chasing</td>
          <td>{{squirrel.Chasing}}</td>
        </tr>
	<tr>
	  <td>Climbing</td>
          <td>{{squirrel.Climbing}}</td>
        </tr>
        <tr>
          <td>Eating</td>
          <td>{{squirrel.Eating}}</td>
        </tr>
        <tr>
          <td>Foraging</td>
          <td>{{squirrel.Foraging}}</td>
        </tr>
        <tr>
          <td>Other Activities</td>
          <td>{{squirrel.Other_Activitites}}</td>
        </tr>
        <tr>
          <td>Kuks</td>
          <td>{{squirrel.Kuks}}</td>
        </tr>
        <tr>
          <td>Quaas</td>
          <td>{{squirrel.Quaas}}</td>
        </tr>
        <tr>
          <td>Moans</td>
          <td>{{squirrel.Moans}}</td>
        </tr>
        <tr>
          <td>Tail flags</td>
          <td>{{squirrel.Tail_flags}}</td>
        </tr>
        <tr>
          <td>Tail twitches</td>
          <td>{{squirrel.Tail_twitches}}</td>
        </tr>
        <tr>
          <td>Approaches</td>
          <td>{{squirrel.Approaches}}</td>
        </tr>
        <tr>
          <td>Indifferent</td>
          <td>{{squirrel.Indifferent}}</td>
        </tr>
        <tr>
          <td>Runs from</td>
          <td>{{squirrel.Runs_from}}</td>
      </tbody>
    </table>
  </body>

</html>

sightings/templates/sightings/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Squirrel Sightings</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head> 
  <body>
    <nav class="navbar navbar-default ">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/sightings">Squirrel Tracker</a></div>
        <ul class="nav navbar-nav ">
          <li>
            <a href="/map">Map</a></li>
	  <li>
            <a href="/sightings/add">Add A New Sighting</a></li>
          <li>
            <a href="/sightings/stats">Statistics</a></li>
        </ul>
      </div>
    </nav>
    <p>Click the link to view and update the sighting detail of each squirrel.</p>
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th>Unique Squirrel ID</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        <tr>
	  {% for squirrel in squirrels %}
	  <td><a href="{% url 'sightings:update' squirrel.Unique_Squirrel_ID %}">{{ squirrel.Unique_Squirrel_ID }}</td>
	  <td>{{squirrel.Date}}</td>
        </tr>
	{% endfor %}
      </tbody>
    </table>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.js"></script>
  </body>
</html>

sightings/templates/sightings/main.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Squirrel List</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.css">
  </head>
  <body>
    <table data-toggle="table">
      <thead>
        <tr>
          <th>Unique Squirrel ID</th>
          <th>Date</th>
          <th>Unique Squirrel Sighting</th>
        </tr>
      </thead>
      <tbody>
        <tr>
	  {% for squirrel in squirrels %}
	  <td>{{squirrel.Unique_Squirrel_ID}}</td>
	  <td>{{squirrel.Date}}</td>
	  <td><a href="{% url 'sighting:detail' squirrel.Unique_Squirrel_ID %}">Sighting</a></td> 
	  {% endfor %}
        </tr>
      </tbody>
    </table>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.js"></script>
  </body>
</html>

sightings/templates/sightings/stats.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Stats of Sightings</title>
  </head>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/4.0.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <body>
    <nav class="navbar navbar-default ">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/sightings">Squirrel Tracker</a></div>
        <ul class="nav navbar-nav ">
          <li>
            <a href="/map">Map</a></li>
          <li>
            <a href="/sightings/add">Add A New Sighting</a></li>
          <li class="active">
            <a href="/sightings/stats">Statistics</a></li>
        </ul>
      </div>
    </nav>
    <h2 style="font-family:verdana;text-align:center;">Statistics of Squirrel sighting data</h2>
    <ul style="list-style-type:square;">
      <li>Total number of sightings: {{a}}</li>
      <br>
      <li>Average of Latitiude：{{b.avg_latitude}}</li>
      <br>
      <li>Average of Longitude: {{c.avg_longitude}}</li>
      <br>
      <li>Shift: {{d}}</li>
      <br>
      <li>Age: {{e}}</li>
      <br>
      <li>Primary fur color: {{f}}</li></ul>
  </body>

</html>

sightings/templates/sightings/update.html
<!DOCTYPE html>

<html lang="en">
<head>
  <title>Update squirrel sighting</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
<p>Updatethe data in the form and save the sighting bu clicking the button at the bottom.</p>
<button type="button" class="btn btn-link"><a href="/sightings">return to sightings page</a></button>
<form method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}

  <input type='submit' value='Save' />
</form>
</div>
</body>
</html>